package proyectofinal.SistemaGestion.Alertas;

public enum AlertType {
    CONTRACT_EXPIRING_SOON,
    PROPERTY_WITHOUT_VISITS,
    HIGH_DEMAND_PROPERTY,
    VISIT_PENDING_CONFIRMATION,
    PROPERTY_RESERVED_WITHOUT_CLOSING,
    CLIENT_WITHOUT_RECENT_FOLLOW_UP
}