package proyectofinal.SistemaGestion.Alertas;

public enum TipoAlerta {
    CONTRATO_PROXIMO_A_VENCER,
    INMUEBLE_SIN_VISITAS,
    PROPIEDAD_ALTA_DEMANDA,
    VISITA_PENDIENTE_POR_CONFIRMAR,
    INMUEBLE_RESERVADO_SIN_CIERRE,
    CLIENTE_SIN_SEGUIMIENTO
}